Update deploy.yaml to pull image from ecr

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -63,6 +63,9 @@ jobs:
           docker push ${{ secrets.ECR_REPO }}:driver-django-${{ github.run_number }}
           docker push ${{ secrets.ECR_REPO }}:driver-database-${{ github.run_number }}
 
+          # echo "DJANGO_IMAGE_TAG=driver-django-${{ github.run_number }}" >> $GITHUB_ENV
+          # echo "DATABASE_IMAGE_TAG=driver-database-${{ github.run_number }}" >> $GITHUB_ENV
+
       - name: SSH into EC2 and Deploy with Docker Compose
         uses: webfactory/ssh-agent@v0.5.3
         with:
@@ -102,12 +105,20 @@ jobs:
             sudo chown -R ubuntu:ubuntu /home/ubuntu/driver-new-tech
             pwd
             ls -al
-            # Ensure Docker Compose is available
+            DJANGO_IMAGE_TAG=driver-django-${{ github.run_number }}
+            DATABASE_IMAGE_TAG=driver-database-${{ github.run_number }}
+            echo $DJANGO_IMAGE_TAG
+            echo $DATABASE_IMAGE_TAG
             sudo apt-get install -y docker-compose
 
             # Pull the latest Docker image from ECR
+            if ! command -v aws &> /dev/null; then
+              echo "AWS CLI not found, installing..."
+              sudo apt-get update -y
+              sudo apt-get install -y awscli
+            fi
             aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}
-            sudo docker-compose pull
+            sudo docker-compose pull $DJANGO_IMAGE_TAG $DATABASE_IMAGE_TAG
 
             # Start or restart the Docker containers using docker-compose
             sudo docker-compose up -d
